name: Deploy to GCS

on:
  push:
    branches:
      - gcs-pipeline

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:  stage
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: set up gcloud
        uses: google-github-actions/setup-gcloud@v2
 
      - name: stage build with unpublsiehd contents
        run: |
          yarn install
          yarn build:unpublished
      - name: echo env variables
        run: |
          echo $EXTENSION_WORKSHOP_BUCKET_GCS
      - name: Run deployment script
        run: |
          bash ./bin/gcs-deploy.sh  code 
         
